[package]
name = "pfs_unpacker"
version = "1.0.0"
edition = "2021"
license = "GPL-3.0"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
rayon = "1.10.0"
sha1 = "0.10.6"
walkdir = "2.5.0"

[dev-dependencies]
assert_cmd = "2.0.16"
