name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Test
        run: cargo test

  build_martix:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: get cache
        uses: Swatinem/rust-cache@v2.7.5

      - name: Build
        run: cargo build --release

      - name: Upload
        uses: actions/upload-artifact@v4.4.3
        with:
          name: pfs_unpacker-${{ runner.os }}-${{ runner.arch }}
          path: target/release/pfs_unpacker
